spring.application.name=library
server.port=8085

app.title=Library
app.description=Educational Spring Boot project.
app.purpose=Learning project
app.version=0.0.1-SNAPSHOT

author.name=Mary
author.email=sidyakina@gmail.com

logging.level.cz.wz.marysidy.library=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n